# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "564e314f27f4550532b039027ad0901f"
name = "price mirror"
handle = "price-mirror-1"
application_url = "https://wives-human-fat-loads.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rukaiya-demo-25.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://wives-human-fat-loads.trycloudflare.com/auth/callback",
  "https://wives-human-fat-loads.trycloudflare.com/auth/shopify/callback",
  "https://wives-human-fat-loads.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
